// LOGIN
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "connorr@test.com",
    "password": "password"
}

###

// REGISTER
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "username": "Connor",
    "email": "connor@test.com",
    "password": "password"
}


###
// NEW ACCESS TOKEN
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBBVUwiLCJpYXQiOjE2NjcyOTE1NTl9.kjkZoZ1eb2CFka-q4fzYWNk7-A8TJrcT3nTsbemdAqo"
}

###
// YOUR USER AUTH CHECK
GET http://localhost:4000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjYzNjE5MWNmMWFiZGZiYmI1ZDUyNTZkMSIsInVzZXJuYW1lIjoiQ29ubm9yIiwiZW1haWwiOiJjb25ub3JAdGVzdC5jb20ifSwiaWF0IjoxNjY3NDQwMjgyLCJleHAiOjE2Njc0NDM4ODJ9.Sr1nGtklBWBhpg34RjsiAwYXuiIBbUvumfsLjtN4abs

###
// ALL USERS
GET http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjYzNjE5MWNmMWFiZGZiYmI1ZDUyNTZkMSIsInVzZXJuYW1lIjoiQ29ubm9yIiwiZW1haWwiOiJjb25ub3JAdGVzdC5jb20ifSwiaWF0IjoxNjY3NDQzOTUwLCJleHAiOjE2Njc0NDc1NTB9.O2SSVgS5p64uhwszpDeGvZTTSUP2pCkw7Uc7HqL-zQE


